### ISSUE TITLE
IndexError: too many indices for array on HTRgene.py

### ISSUE THREAD

**Issue by papelypluma** [hongryulahn/HTRgene#1]
Hi HTRgene developers,

I have been attempting to run the tool on the actual dataset and on the test/example dataset, but unfortunately  the HTRgene.py script keeps throwing an IndexError:

> File "/tools/HTRgene/HTRgene.py", line 754, in <module>
>     dic_gene2phase, dic_phase2rt = run(lst_sample=lst_sample, lst_gene=lst_gene, arr_exp=arr_exp, DEGpcut=args.DEGpcut, minClusterSize=args.minClusterSize, step2_k=args.step2_k, platform=args.platform, seed=args.seed, outdir=args.o)
>   File "/tools/HTRgene/HTRgene.py", line 653, in run
>     arr_DEG[:,s] = np.max(abs(arr_DEGpre[:,lst_i]),axis=1)
> IndexError: too many indices for array

I was wondering if you can help us look into this error.
 
Thank you.

**Comment by papelypluma** [comment]
Figured out that a specific version of statsmodels had to be installed. Both 0.9.1 and 0.10.1 worked.

**Comment by ytshushushu** [comment]
Hi , I also got the same error, why did I still get the same error after installing the statsmodels ?
